# Generated by Django 3.1.7 on 2021-03-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
    ]
