# Generated by Django 3.1.7 on 2021-03-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_album_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
